import {
  createContext,
  useCallback,
  useContext,
  useMemo,
  useState,
  type ReactNode,
} from 'react';
import { todayIso, addDaysIso } from '../lib/date';
import type { Guest } from '../types/guest';

// SESSION-SCOPED create-booking DRAFT (build 6b fix).
//
// The create-booking form used to live inside CreateBookingDialog, so leaving the
// bookings screen and coming back discarded a half-filled booking — a receptionist
// pulled away to check something lost their work. This provider lifts the form
// state above the admin routes so it survives navigation WITHIN the admin shell.
//
// DELIBERATELY IN-MEMORY ONLY, per CLAUDE.md's no-browser-storage rule: NO
// localStorage, NO sessionStorage, NO database. A full page refresh or closing the
// tab clears it — that is acceptable and expected for a session-scoped draft. This
// is not persistence; it is "don't lose my work when I click over to another
// screen and back". The mount point (App.tsx, above the admin <Outlet/>) is what
// makes it survive route changes: the provider is not unmounted when the child
// route changes, only the screen under it is.
//
// SCOPED BY PROPERTY: drafts are keyed by propertyId. Switching the active property
// must never show one property's draft against another, so each property gets its
// own slot; the old property's draft is simply parked in the map, untouched, and
// the new property sees its own draft (or a fresh default). BookingsScreen is keyed
// by property id, so it reads the right slot automatically.

// The new-guest inline sub-form's persisted fields (the guest SEARCH box and its
// results are transient and reload, so they are not part of the draft). Structured
// name + ID document (018) — first/last are what a new guest needs, the rest is
// optional, and every keystroke survives navigating away and back.
export interface NewGuestDraft {
  creating: boolean;
  firstName: string;
  lastName: string;
  middleName: string;
  phone: string;
  email: string;
  idType: string;
  idNumber: string;
  idExpiry: string;
}

// Everything the create-booking form holds that must survive navigation. Loaded /
// derived data (room types, companies, availability, the rate quote) is NOT here —
// it is recomputed on mount and never was form input.
export interface BookingDraft {
  open: boolean;
  checkIn: string;
  checkOut: string;
  roomTypeId: string;
  companyId: string;
  guest: Guest | null;
  newGuest: NewGuestDraft;
  adults: number | null;
  children: number | null;
  specialRequests: string;
  // 'HH:MM' or '' — the expected arrival time the guest mentioned (025). Form
  // input, so it belongs in the draft and survives navigating away like every
  // other field. Optional and informational; '' means "not said".
  expectedArrivalTime: string;
  // A fresh key per submit INTENT (rule 2/3 guard). Held in the draft so a booking
  // resumed after navigating away submits under the same key; regenerated by the
  // dialog after an availability exception (a genuinely new attempt).
  idempotencyKey: string;
}

// A fresh idempotency key. crypto.randomUUID needs no storage (constraint).
function newIdempotencyKey(): string {
  return crypto.randomUUID();
}

// A blank draft. Dates default to tonight → tomorrow; computed fresh each time a
// draft is opened so a long-lived tab does not default to a stale "today".
function makeDefaultDraft(): BookingDraft {
  const today = todayIso();
  return {
    open: false,
    checkIn: today,
    checkOut: addDaysIso(today, 1),
    roomTypeId: '',
    companyId: '',
    guest: null,
    newGuest: {
      creating: false,
      firstName: '',
      lastName: '',
      middleName: '',
      phone: '',
      email: '',
      idType: '',
      idNumber: '',
      idExpiry: '',
    },
    adults: 1,
    children: 0,
    specialRequests: '',
    // Blank by default, NOT "now" or a house check-in time: an unasked question
    // must not arrive on the booking as an answer the desk never got.
    expectedArrivalTime: '',
    idempotencyKey: '',
  };
}

interface BookingDraftContextValue {
  drafts: Record<string, BookingDraft>;
  defaultDraft: BookingDraft;
  update: (propertyId: string, patch: Partial<BookingDraft>) => void;
  clear: (propertyId: string) => void;
  open: (propertyId: string) => void;
}

const BookingDraftContext = createContext<BookingDraftContextValue | undefined>(
  undefined,
);

export function BookingDraftProvider({ children }: { children: ReactNode }) {
  // The whole store: one draft per property, in memory only. Nothing is read from
  // or written to any storage — losing this on refresh is by design.
  const [drafts, setDrafts] = useState<Record<string, BookingDraft>>({});

  // A single stable "empty" draft returned for any property with no slot yet, so
  // reads before the first edit have a consistent identity (no effect thrash).
  // Lazy useState init (not a ref) keeps a stable value without a during-render
  // ref access.
  const [defaultDraft] = useState(makeDefaultDraft);

  // The three mutators are STABLE (useCallback): each drives setDrafts through the
  // functional updater, so none closes over `drafts` and none needs to change when
  // `drafts` changes. A stable identity matters — `clear` is handed to the dialog
  // as its onClose, which feeds useFocusTrap; a fresh identity per render there
  // re-runs the focus trap and steals focus on every keystroke. Keeping these
  // stable also stops the whole consumer subtree from re-rendering on identity
  // churn alone.
  const update = useCallback(
    (propertyId: string, patch: Partial<BookingDraft>) => {
      setDrafts((prev) => ({
        ...prev,
        [propertyId]: { ...(prev[propertyId] ?? defaultDraft), ...patch },
      }));
    },
    [defaultDraft],
  );

  // Clearing removes the property's slot entirely, so it reverts to the blank
  // default. Called on a successful submission AND on cancel/close — but never on
  // navigation, which simply leaves the slot in place.
  const clear = useCallback((propertyId: string) => {
    setDrafts((prev) => {
      if (!(propertyId in prev)) return prev;
      const next = { ...prev };
      delete next[propertyId];
      return next;
    });
  }, []);

  // Opening the dialog: mark it open and ensure a submit-intent key. A fresh draft
  // is materialised with current-day dates; an existing in-progress draft is
  // reopened as-is (keeping its key).
  const open = useCallback((propertyId: string) => {
    setDrafts((prev) => {
      const existing = prev[propertyId];
      const base = existing ?? makeDefaultDraft();
      return {
        ...prev,
        [propertyId]: {
          ...base,
          open: true,
          idempotencyKey: base.idempotencyKey || newIdempotencyKey(),
        },
      };
    });
  }, []);

  const value = useMemo<BookingDraftContextValue>(
    () => ({ drafts, defaultDraft, update, clear, open }),
    [drafts, defaultDraft, update, clear, open],
  );

  return (
    <BookingDraftContext.Provider value={value}>
      {children}
    </BookingDraftContext.Provider>
  );
}

export interface UseBookingDraftResult {
  draft: BookingDraft;
  update: (patch: Partial<BookingDraft>) => void;
  updateNewGuest: (patch: Partial<NewGuestDraft>) => void;
  clear: () => void;
  open: () => void;
}

// The per-property view of the draft. `propertyId` scopes every operation to that
// property's slot (rule: one property's draft never leaks to another).
export function useBookingDraft(propertyId: string): UseBookingDraftResult {
  const ctx = useContext(BookingDraftContext);
  if (ctx === undefined) {
    throw new Error('useBookingDraft must be used within a BookingDraftProvider');
  }

  const draft = ctx.drafts[propertyId] ?? ctx.defaultDraft;

  // Bind each mutator to this property ONCE and keep the identity stable: the
  // underlying ctx functions are stable and propertyId rarely changes, so these
  // no longer churn per render. That stability is what keeps `clear` (used as the
  // dialog's onClose, which feeds useFocusTrap) from re-arming the focus trap on
  // every keystroke.
  const update = useCallback(
    (patch: Partial<BookingDraft>) => ctx.update(propertyId, patch),
    [ctx, propertyId],
  );
  const clear = useCallback(() => ctx.clear(propertyId), [ctx, propertyId]);
  const open = useCallback(() => ctx.open(propertyId), [ctx, propertyId]);
  // Shallow-merge the nested new-guest sub-object (a plain spread would drop the
  // other new-guest fields). This reads draft.newGuest from the current render, so
  // its identity changes with the draft — that is fine: it is only ever an event
  // handler, never an effect dependency.
  const updateNewGuest = (patch: Partial<NewGuestDraft>) =>
    ctx.update(propertyId, { newGuest: { ...draft.newGuest, ...patch } });

  return { draft, update, updateNewGuest, clear, open };
}
