// Row types for the stock take (migration 039).
//
// EVERY NUMERIC FIELD BELOW IS A `number`, ALREADY PARSED (rule 24). This file
// is the clearest illustration of why the parse belongs at the boundary: the
// counts in stock_take_progress are cast to `integer` in the view so they
// arrive as JSON NUMBERS, while the quantities beside them are numeric and
// arrive as STRINGS — two shapes, one row, decided by a cast in a migration
// that no component can see. src/lib/stockTake.ts parses both on the way in, so
// the difference stops at the data layer where it belongs.
//
// ---------------------------------------------------------------------------
// THE NULLS IN HERE ARE THE FEATURE, NOT AN ABSENCE OF DATA
// ---------------------------------------------------------------------------
// Two different NULLs matter, and confusing them is the whole failure mode this
// shipment exists to prevent:
//
//   counted_quantity === null   NOT COUNTED. Nobody has been to that shelf. It
//                               produces no movement and no variance. It is NOT
//                               zero, and it must never render as "0".
//   expected_quantity === null  BLIND. The count is still open (or was
//                               cancelled), so the server did not send the
//                               figure at all — see 039 §4. It is NOT "the item
//                               has nothing", and it must never render as "0"
//                               either.

// 040 adds the fourth state. Every arrow between them is one-way:
//   open --finish--> finished --reverse--> reversed
//     \--cancel--> cancelled
// A count that was wrong is answered by another count, never by re-opening this
// one — so there is no transition back and no 'delete'.
export type StockTakeStatus = 'open' | 'finished' | 'cancelled' | 'reversed';

// stock_takes — the document itself. What the four RPCs return.
//
// NOTE what is NOT here: there is no expected quantity anywhere on the header,
// and no variance total. Those live on the lines and come back only through
// stock_take_sheet / stock_take_progress, which know when they may be shown.
export interface StockTake {
  id: string;
  tenant_id: string;
  property_id: string;
  location_id: string;
  // 'ST-000004'. Generated by the shared per-tenant counter (015 §2), never by
  // counting rows — a count is referred to out loud, so it needs a name.
  take_number: string;
  // The OPERATING DAY the count belongs to (rules 8/12) — an ISO 'YYYY-MM-DD'.
  // Every movement the count posts carries this date, not the day Finish was
  // pressed.
  business_date: string;
  status: StockTakeStatus;
  note: string | null;
  started_at: string;
  started_by: string | null;
  finished_at: string | null;
  finished_by: string | null;
  // The manager whose PIN authorised finishing. NULL means the variance was
  // within the property's threshold and the person finishing acted on their own
  // authority — still named, in finished_by.
  approved_by: string | null;
  cancelled_at: string | null;
  cancelled_by: string | null;
  cancel_reason: string | null;
  // 040. Undoing a count ALWAYS needs a manager PIN, with no threshold — unlike
  // finishing one, which is gated by the property's variance threshold — so
  // reverse_approved_by is never null on a reversed count.
  reversed_at: string | null;
  reversed_by: string | null;
  reverse_approved_by: string | null;
  reverse_reason: string | null;
  idempotency_key: string | null;
  close_idempotency_key: string | null;
  reverse_idempotency_key: string | null;
  created_at: string;
  updated_at: string;
  created_by: string | null;
  updated_by: string | null;
}

// stock_take_progress — the document with its sheet counted up (039 §4.2).
//
// Nothing here is stored: every figure folds from the lines on read (rule 6).
// The counted/uncounted pair is visible while the count is OPEN and that is not
// a leak — knowing 40 of 180 shelves have been visited says nothing about what
// is on them. The variance figures are NULL until the count is finished.
export interface StockTakeProgressRow {
  stock_take_id: string;
  tenant_id: string;
  property_id: string;
  location_id: string;
  location_name: string;
  take_number: string;
  status: StockTakeStatus;
  business_date: string;
  note: string | null;
  started_at: string;
  started_by: string | null;
  finished_at: string | null;
  finished_by: string | null;
  approved_by: string | null;
  cancelled_at: string | null;
  cancelled_by: string | null;
  cancel_reason: string | null;
  reversed_at: string | null;
  reversed_by: string | null;
  reverse_approved_by: string | null;
  reverse_reason: string | null;
  // integer in the view → a JSON NUMBER on the wire.
  line_count: number;
  counted_count: number;
  uncounted_count: number;
  // 040. HOW MUCH OF THIS COUNT IS STILL STANDING. These two differ from the
  // status when individual lines were reversed from the item ledger rather than
  // the whole document being undone — which is exactly the case worth seeing,
  // and the reason they are separate numbers rather than a boolean.
  movement_count: number;
  reversed_movement_count: number;
  // NULL until finished (blind) — see the note at the top.
  variance_count: number | null;
  // numeric(14,2). Signed: what the count changed the stock value by.
  net_variance_value: number | null;
  // The size of the discrepancy regardless of direction — the figure the
  // property's approval threshold is measured against.
  absolute_variance_value: number | null;
}

// stock_take_sheet — one row per line, for BOTH faces of the sheet (039 §4.1).
// The same view serves the open count and the finished variance report; the
// status decides which columns carry values, so there is one definition of what
// a variance is rather than two that can drift.
export interface StockTakeSheetRow {
  line_id: string;
  tenant_id: string;
  stock_take_id: string;
  property_id: string;
  location_id: string;
  take_status: StockTakeStatus;
  business_date: string;
  inventory_item_id: string;
  item_name: string;
  item_code: string | null;
  base_unit: string;
  category_id: string | null;
  item_is_active: boolean;
  category_name: string | null;

  // ALWAYS SENT. What the counter typed is theirs to read back — that is what
  // makes a resumed count possible at all. NULL means NOT COUNTED.
  counted_quantity: number | null;
  // Derived in the view from NULL-ness, so a counted ZERO is `true` here. It is
  // a real column so the "still to count" filter runs server-side (rule 1b).
  is_counted: boolean;
  counted_at: string | null;
  counted_by: string | null;

  // BLIND UNTIL FINISHED. All four are NULL while the count is open and stay
  // NULL forever on a cancelled count (039 §4).
  expected_quantity: number | null;
  variance_quantity: number | null;
  variance_unit_cost: number | null;
  variance_value: number | null;

  movement_id: string | null;
  // 040. Whether this line's posting has since been undone — by the whole count
  // being reversed, or by somebody reversing that one movement from the item's
  // ledger. Derived in the view, never stored (rule 6).
  movement_reversed: boolean;
}

// What record_count_line returns — deliberately NARROW (039 §6.2). Returning
// the stock_take_lines row type would have serialised expected_quantity past
// every guard in §4, so the RPC returns only the fields the caller may know.
export interface CountLineResult {
  line_id: string;
  stock_take_id: string;
  inventory_item_id: string;
  counted_quantity: number | null;
  counted_at: string | null;
  counted_by: string | null;
}
